import { createBlock, createConfig, createGroup, createPanel, createLabel } from './config.builder';

export default createConfig('http://47.89.8.92:3008/v1', '64468f8f585ce246c264')
	.setName('Gateway Manager')
    .addGroup( createGroup()
		.setName('Gateways')
		.addPanel( createPanel('644690130699e6fbd4a2', '64895f70d9a400b1b039')
		    .setName('Gateways')
			.addLabel(createLabel('userID').setQueries([]))
		    .addBlock(createBlock('gwID'))
		    .addBlock(createBlock('gwModel'))
		    .addBlock(createBlock('gwIP'))
		    .addBlock(createBlock('service'))
		    .addBlock(createBlock('region'))
		    .addBlock(createBlock('serverAddr'))
		    .addBlock(createBlock('status')))
	)
	.addGroup( createGroup()
		.setName('System')
		.addPanel( createPanel('644690130699e6fbd4a2', '646f02c8e3121a20c41c')	
		.setName('Profile')
		.addBlock(createBlock('name'))
		.addBlock(createBlock('description')))
	)